# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPPlwls2d_s1 <- function(bw, kernel_type, win, tin, yin, xin, zin, tout, npoly = 1L, nder = 0L) {
    .Call(`_MMVCM_CPPlwls2d_s1`, bw, kernel_type, win, tin, yin, xin, zin, tout, npoly, nder)
}

CPPlwls2d_s2 <- function(bw, kernel_type, win, tin, yin, xin, tout, npoly = 1L, nder = 0L) {
    .Call(`_MMVCM_CPPlwls2d_s2`, bw, kernel_type, win, tin, yin, xin, tout, npoly, nder)
}

CPPlwls2d_s2_LR <- function(bw, kernel_type, win, tin, yin, xin, tout, npoly = 1L, nder = 0L) {
    .Call(`_MMVCM_CPPlwls2d_s2_LR`, bw, kernel_type, win, tin, yin, xin, tout, npoly, nder)
}

